name: cd-gh-pages

on:
  push:
    branches:
      - main

jobs:
  cd-gh-pages:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@mv4.2.0

      - name: Setup node env
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn generate

      - name: Deploy
<<<<<<< HEAD
        uses: peaceiris/actions-gh-pages@v4.0.0
=======
        uses: peaceiris/actions-gh-pages@v4
>>>>>>> 71a4e1118d48111c0dc9c6831629da1dc5387b40
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
